100.learn-more-about-oceanbase=OceanBase の紹介
  400.compatibility-with-oracle=Oracle との互換性比較
200.quickstart=クイックスタート
  200.get-started-with-oceanbase-sql=OceanBase SQL を学ぶ
  300.create-sample-application-of-mysql-mode=MySQL スキーマでサンプルアプリケーションを作成する
  300.create-sample-application-of-oracle-mode=Oracle スキーマでサンプルアプリケーションを作成する
  500.experience-advanced-features-of-oceanbase=OceanBase の高度な機能を体験する
    100.experience-scalable-oltp=スケーラブルな OLTP の体験
400.deploy=データベースの展開
  300.deploy-oceanbase-enterprise-edition=OceanBase エンタープライズエディションの展開
    200.preparations-before-deploy=展開前の準備
    300.deploy-through-a-graphical-interface=GUI を使用した展開
      100.configuring-the-deploy-environment-through-oat=OAT を使用した展開環境の設定
      200.deploy-ocp-use-oat=OCP の展開
      300.deploy-oceanbase-cluster-use-ocp=OCP を使用して OceanBase クラスタを展開する
    400.deploy-through-the-command-line=コマンドラインを使用した展開
      100.configure-a-deployment-environment-command-line=oatcli を使用した展開環境の設定
      200.deploy-the-oceanbase-cluster-command-line=コマンドラインを使用して OceanBase クラスタを展開す
  500.deploy-oceanbase-database-community-edition=OceanBase コミュニティエディションの展開
    200.local-deployment=ローカル展開
      200.environment-and-configuration-checks=展開前の設定
      400.deploy-by-ui=GUI を使用した展開