100.oceanbase-database-overview=Overview
200.quick-start=Get Started
  200.Hands-on-for-OceanBase-SQL=Hands on for OceanBase SQL
  300.Create-a-sample-application=Create a sample application
  400.Experience-OceanBase-Advanced-Features=Experience OceanBase advanced features
    100.Experience-Scalable-OLTP=Experience scalable OLTP
300.developer-guide=Develop
  100.client-connects-to-oceanbase-database=Connect to Oceanbase Database with client
    600.c-application=C application
    1400.database-connection-pool-configuration-example=Example of Database connection pool configuration
  200.create-and-manage-database-objects=Create and manage database objects
    400.data-type=Data type
    600.create-and-manage-tables=Create and manage tables
    700.create-and-manage-partition-table=Create and manage partition tables
    800.create-and-manage-indexes=Create and manage indexes
    1000.create-and-manage-views=Create and manage views
    1100.managing-and-creating-sequences=Create and manage sequences
  300.query=Query
    800.multi-table-join-queries=Query data from multiple tables
    900.use-operators-and-functions-in-queries=Use operators and functions in a query
    1000.execution-plan=Execution plan
  400.about-dml-statements-and-transactions=DML statements and transactions
    100.dml-statement=DML statement
    200.transaction=Transactions
  500.common-errors-and-solutions-mysql=Common errors and solutions
    0300.timeout=About timeout
    0400.user-2=About user
    0500.table-related-functions=About table
    0600.constraint-related-functions=About constraint
    0700.sql-related-commands=About SQL commands
400.installation-and-deployment=Deploy
  200.local-deployment=On-premises deployment
  400.highly-available-deployment=High availability deployment
600.data-migration=Migrate
  200.migrate-data-from-MySQL-database-to-OceanBase-database=Migrate data from MySQL Database to OceanBase
  400.migrate-data-from-CSV-file-to-OceanBase-database=Migrate data from CSV-file to OceanBase
  700.migrate-data-from-OceanBase-database-to-MySQL=Migrate data from OceanBase Database to MySQL
