100.oceanbase-database-overview=OceanBase 简介
200.quick-start=快速上手
  100.Getting-started-with-OceanBase-SQL=上手 OceanBase SQL
  200.Create-a-sample-application=创建示例应用程序
  300.Experience-the-advanced-features-of-OceanBase=体验 OceanBase 高级特性
    100.Experience-Scalable-OLTP=体验 Scalable OLTP
300.developer-guide=应用开发
  100.client-connects-to-oceanbase-database=客户端连接 OceanBase 数据库
    1400.database-connection-pool-configuration-example=数据库连接池配置示例
    600.c-application=C 应用程序
  200.create-and-manage-database-objects=创建和管理数据库对象
		400.data-type=数据类型
		600.create-and-manage-tables=创建和管理表
		700.create-and-manage-partition-table=创建和管理分区表
		800.create-and-manage-indexes=创建和管理索引
    1000.create-and-manage-views=创建和管理视图
		1100.managing-and-creating-sequences=创建和管理序列
    1200.create-and-manage-triggers=创建和管理触发器
  300.query=查询
    800.multi-table-join-queries=多表关联查询
    900.use-operators-and-functions-in-queries=在查询中使用操作符和函数
    1000.execution-plan=执行计划
  400.about-dml-statements-and-transactions=关于 DML 语句和事务
    100.dml-statement=DML 语句
    200.transaction=事务
  500.common-errors-and-solutions-mysql=MySQL 模式下常见报错
    300.timeout=超时相关
    400.user-2=用户相关
    500.table-related-functions=表相关
    600.constraint-related-functions=约束相关
    700.sql-related-commands=SQL 相关
400.installation-and-deployment=部署数据库
  200.local-deployment=本地部署
  400.highly-available-deployment=高可用部署
500.administrator-guide=管理数据库
  500.database-connection-and-routing=数据库连接和路由
    200.obproxy-management=管理 OBProxy
      200.manage-obproxy-clusters=管理 OBProxy 集群
      300.obproxy-management=管理 OBProxy
    300.database-connection=连接数据库
    500.logical-connection=逻辑连接
    600.driver-management=驱动管理
    700.route-management=路由管理
      400.odp-routing-policy=ODP 路由策略
  600.basic-database-management=集群和多租户管理
    100.manage-clusters=管理集群
      300.manage-cluster-parameters=管理集群参数
      400.manage-zones-in-a-cluster=管理集群中的 Zone
      500.manage-observers=管理 OBServer
    200.configuration-management=配置管理
    300.manage-resources=管理资源
      300.manage-resource-units=管理资源单元
      500.manage-resource-pools-1=管理资源池
    400.manage-tenants-1=管理租户
      400.manage-tenants-2=管理租户
      500.manage-users-and-permissions=管理用户和权限
        100.users-and-permissions=用户及权限介绍
        300.mysql-3=MySQL 模式
      1300.manage-tenant-parameters=管理租户参数
    500.manage-data-storage=管理数据存储
      100.dump-management-1=转储管理
      200.merge-management-1=合并管理
      300.data-compression-1=数据压缩
    700.memory-management-1=管理内存
    800.management-process=管理进程
    900.manage-logs=管理日志
      200.log-print-level=日志打印级别
      300.manage-the-size-and-quantity-of-log-files-2=日志文件大小及数量管理
      400.view-logs-2=查看日志
  700.database-object-management=数据库对象管理
    100.manage-databases=管理数据库
    200.manage-tables=管理表
    400.manage-indexes=管理索引
  800.distributed-storage-management=分布式存储管理
    200.manage-partition-table=管理分区
      900.create-partition-table-index-3=创建分区表索引
    400.manage-replicas=管理副本
    500.locality-management-1=管理 Locality
  900.performance-tuning-guide=性能调优
    200.performance-related-tools=性能相关工具
      100.system-tools=系统工具
      200.internal-table=内部表
      300.log-information=日志
    300.system-tuning=系统调优
      200.database-parameter-tuning=数据库参数调优
      300.obproxy-parameter-optimization=OBProxy 参数调优
    400.business-model-tuning=业务模型调优
    500.sql-optimization=SQL 调优指南
      200.sql-execution-plan=SQL 执行计划
        200.execution-plan-operator=执行计划算子
      300.distributed-execution-plan=分布式执行计划
      400.sql-optimization-1=SQL 调优
        300.monitor-sql-execution-performance=SQL 执行性能监控
          400.sql-performance-analysis-example=SQL 性能分析示例
        400.optimizer-statistics=优化器统计信息
          200.statistics-collection-methods=统计信息收集方式
          300.statistics-management=统计信息管理
        500.query-rewrite=查询改写
        600.query-optimization=查询优化
          100.access-path=访问路径
          200.join-algorithm=联接算法
        700.manage-execution-plans=管理执行计划
    600.performance-whitepaper=性能测试
  1000.high-data-availability=高可用和容灾
    100.administrator-guide-flashback=闪回
    200.backup-and-restoration-management=备份恢复管理
      300.log-archive=日志归档
      400.data-backup=数据备份
      500.cleaning-up-backed-up-data=清理备份
      600.restore-data=恢复数据
  1100.operation-and-maintenance-management=运维管理
    200.scale-out-and-scale-in-1=扩容和缩容
      200.cluster-level-scale-out-and-scale-in=集群级别的扩容和缩容
        100.scale-out=扩容
        200.shrink-1=缩容
      300.scale-in-and-scale-out-of-tenant-resources=租户内资源的扩容和缩容
    400.monitoring-and-alerting=监控和告警
      200.monitoring-1=监控
      300.alert-1=告警
    500.daily-inspection=日常巡检
      200.full-link-detection=全链路诊断
    600.performance-diagnosis=性能诊断
    800.emergency-response=应急处理
    300.common-emergency-response=常见应急问题处理
      100.issues-in-the-hardware-environment=硬件环境导致的问题
      200.problems-caused-by-capacity-changes=容量变化导致的问题
      300.other-problems-within-the-cluster=集群内部其他问题
  1200.data-security-management=数据库安全
600.data-migration=数据迁移
  200.migrate-data-from-MySQL-database-to-OceanBase-database=从 MySQL 迁移到 OceanBase 数据库
  400.migrate-data-from-CSV-file-to-OceanBase-database=从 CSV 文件迁移数据到 OceanBase 数据库
  700.migrate-data-from-OceanBase-database-to-MySQL=从 OceanBase 迁移到 MySQL 数据库
700.reference=参考指南
  100.oceanbase-database-concepts=系统架构
    300.multi-tenant-architecture-1=多租户架构
      500.tenants-and-resource-management-1=租户与资源管理
    400.database-objects-1=数据库对象
      100.introduction-to-database-objects-1=数据库对象介绍
      200.table-1=表
        200.data-type-3=数据类型
      300.index-1=索引
      400.partition-2=分区
      500.view-2=视图
      600.system-view-2=系统视图
      700.data-integrity-1=数据完整性
        200.integrity-constraint-type-1=完整性约束类型
    500.distributed-database-objects=分布式数据库对象
      300.data-partitions-and-replicas=数据分区和分区副本
        300.partition-replica-type=分区副本类型
      400.dynamic-scaling=动态扩容和缩容
        200.scale-in-and-scale-out-of-tenant-resources-1=租户内资源的扩容和缩容
    600.data-link-1=数据链路
      200.database-proxy-1=数据库代理
    700.user-interface-and-query-language=用户接口和查询语言
      100.SQL=SQL
        100.sql-introduction=SQL 介绍
        200.sql-statement-2=SQL 语句
        500.distributed-execution-plan-2=分布式执行计划
      200.PL=PL
    800.transaction-management-1=事务管理
      100.transaction-2=事务
        500.transaction-control=事务控制
        800.distributed-transactions-1=分布式事务
      200.transaction-concurrency-and-consistency=事务并发和一致性
        300.concurrency-control-1=并发控制
        400.transaction-isolation-level=事务隔离级别
    900.storage-architecture-1=存储架构
      200.data-storage=数据存储
      300.dump-and-merge-1=转储和合并
      600.data-integrity-2=数据完整性
    1000.high-data-reliability-and-availability=数据可靠性和高可用
      100.high-availability-architecture=高可用架构
      400.data-protection=数据保护
      500.backup-and-restoration=备份恢复
    1100.database-security=数据安全
    1200.observer-node-architecture=OBServer 节点架构
      300.observer-thread-model=observer 线程模型
      500.memory-management=内存管理
  200.sql-syntax=SQL 语句
    100.system-tenants=系统租户
      200.alter-system=ALTER SYSTEM
    200.common-tenant-mysql-mode=普通租户
      100.basic-elements=基本元素
        100.data-type=数据类型
          200.numeric-1=数值类型
          300.date-and-time-types-1=日期时间类型
          400.string-2=字符类型
          500.large-object-1=大对象和文本类型
          800.json-formatted-data-type=JSON 数据类型
        200.expression-2=表达式
        300.character-set-and-collation=字符集与字符序
        400.literal=字面量
      200.operator=运算符
      400.functions=函数
        200.functions-1=单行函数
          100.date-and-time-functions-1=日期时间函数
          200.string-functions=字符串函数
          300.conversion-functions-1=转换函数
          400.mathematical-functions=数学函数
          500.comparison-functions=比较函数
          600.process-control-functions=流程控制函数
        300.aggregate-function=聚合函数
        400.analysis-functions-1=分析函数
        500.encryption-functions=加密函数
        600.information-functions=信息函数
        700.json-functions=JSON 函数
          100.create-a-function-with-json-text=创建 JSON 文本的函数
          200.a-function-to-search-for-json-text=搜索 JSON 文本的函数
          300.function-to-modify-json-text=修改 JSON 文本的函数
          400.function-that-returns-the-json-text-property=返回 JSON 文本属性的函数
          500.json-functions-1=JSON 工具函数
          600.json-aggregate-functions=JSON 聚合函数
        800.other-functions=其它函数
      500.queries-and-subqueries=查询和子查询
      600.sql-statement=SQL语句
        5100.SELECT-1-2=SELECT
      700.ddl-function=DDL 功能
  300.system-views=系统视图
    200.dictionary-view-5=字典视图
    300.performance-view-5=性能视图
  400.system-variables=系统变量
  500.system-configuration-items=系统配置项
    300.cluster-level-configuration-items-1=集群级别配置项
    400.tenant-level-configuration-items-1=租户级别配置项
  600.error-codes=错误码
  800.supporting-tools=生态工具
    100.ob-admin=ob_admin
      300.clog=clog
    200.ob-agent=OBAgent
      100.about-obagent=关于 OBAgent
      200.configuration-reference=配置引用
      300.install-and-deploy-obagent=安装部署
      400.obagent-metrics=OBAgent 指标
    400.cdc=CDC
      200.obcdc=obcdc
        100.deploy-and-use-obcdc=obcdc 部署和使用
        200.obcdc-parameters=obcdc 参数说明
      300.oblogproxy=oblogproxy
        100.install-and-deploy-oblogproxy=oblogproxy 安装部署
      400.oblogmsg=oblogmsg
    1000.mysqltest=mysqltest
      200.use-of-case=case 使用
900.releasenotes=版本发布记录
  9900.V4.0=V4.0
  10000.V3.1=V3.1
