100.oceanbase-database=关于 OceanBase 数据库
200.quick-start=快速入门
  600.basic-operations=基本操作
300.performance-whitepaper=性能白皮书
400.installation-and-deployment=安装部署
500.oceanbase-database-overview=OceanBase 数据库系统概念
  100.introduction-to-oceanbase-database=OceanBase 数据库简介
  200.multi-tenant-architecture=多租户架构
    500.tenant-and-resource-management=租户与资源管理
  300.database-objects=数据库对象
    200.mysql-mode=MySQL 模式
      100.mysql-mode-introduction-to-database-objects=数据库对象介绍
      200.mysql-mode-tables=表
        200.mysql-mode-data-types=数据类型
      300.mysql-mode-indexes=索引
      400.mysql-mode-partitions=分区
      500.mysql-mode-views=视图
      600.mysql-mode-system-views=系统视图
      700.mysql-mode-data-integrity=数据完整性
        200.mysql-mode-types-of-integrity-constraints=完整性约束类型
  400.distributed-database-objects=分布式数据库对象
    300.partitions-and-replicas=数据分区和分区副本概述
      200.replica-types=分区副本类型
      400.data-balancing=数据均衡
        100.replica-balancing=分区副本均衡
        200.leader-balancing=Leader 均衡
    400.dynamic-scale-out-and-scale-in=动态扩容和缩容
      200.scale-out-and-scale-in-of-tenant-resources=租户内资源的扩容和缩容
  500.data-links=数据链路
    200.database-proxy=数据库代理
    300.database-drivers=数据库驱动
  600.user-interfaces-and-query-languages=用户接口和查询语言
    100.sql=SQL
      100.introduction-to-sql=SQL 介绍
      200.oceanbase-database-overview-sql-statements=SQL 语句
      500.distributed-execution-plans=分布式执行计划
    200.pl=PL
      100.pl-concepts=PL 概念
        100.pl-oracle-mode=Oracle 模式
        200.pl-mysql-mode=MySQL 模式
  700.transaction-management=事务管理
    100.transactions=事务
      500.transaction-control=事务控制
        400.transaction-control-statements=事务控制语句
      800.distributed-transactions=分布式事务
    200.transaction-concurrency-and-consistency=事务并发和一致性
      300.concurrency-control=并发控制
      400.transaction-isolation-levels=事务隔离级别
  800.storage-architecture=存储架构
    200.data-storage=数据存储
    300.minor-compaction-and-major-compaction=转储和合并
    600.storage-architecture-data-integrity=数据完整性
  900.data-reliability-and-high-availability=数据可靠性和高可用
    100.high-availability-architecture=高可用架构
    400.data-protection=数据保护
    500.backup-and-recovery=备份恢复
  1000.database-security=数据库安全
  1100.observer-architecture=OBServer 节点架构
    300.observer-threading-model=observer 线程模型
    500.oceanbase-database-overview-memory-management=内存管理
600.administrator-guide=管理员指南
  100.introduction-to-database-management=数据库管理入门
    300.administrator-guide-connect-to-oceanbase-database=连接数据库
    400.view-your-database-version=查看您的数据库版本
  200.basic-database-management=数据库基础管理
    100.manage-clusters=管理集群
      300.manage-cluster-parameters=管理集群参数
      400.manage-zones-in-a-cluster=管理集群中的 Zone
      500.manage-observers=管理 OBServer
    200.configuration-management=配置管理
    300.manage-resources=管理资源
      300.manage-resource-units=资源管理单元
      500.manage-resource-pools=管理资源池
    400.manage-tenants=管理租户
      400.administrator-guide-manage-tenants=管理租户
      500.manage-users-and-privileges=管理用户和权限
        100.introduction-to-users-and-privileges=用户及权限介绍
      1300.manage-tenant-parameters=管理租户参数
    500.manage-data-storage=管理数据存储
      100.minor-compaction-management=转储管理
      200.major-compaction-management=合并管理
        500.view-major-compaction-information=查看合并信息
    600.manage-memory=管理内存
    700.manage-processes=管理进程
    800.manage-logs=管理日志
      200.administrator-guide-log-print-level=日志打印级别
      300.manage-the-size-and-number-of-log-files=日志文件大小及数量管理
      400.view-logs=查看日志
    900.scale-out-and-scale-in=扩容和缩容
      200.cluster-level-scale-out-and-scale-in=集群级别的扩容和缩容
        100.scale-out=扩容
        200.scale-in=缩容
      300.administrator-guide-scale-out-and-scale-in-of-tenant-resources=租户内资源的扩容和缩容
  300.database-connection-and-routing=数据库连接和路由
    300.logical-connection=逻辑连接
    400.driver-management=驱动管理
    500.routing-management=路由管理
      400.odp-routing-policy=ODP 路由策略
  400.database-object-management=数据库对象管理
    100.manage-databases=管理数据库
    200.manage-tables=管理表
    300.manage-table-groups=管理表组
    400.manage-indexes=管理索引
  500.distributed-storage-management=分布式存储管理
    200.manage-partitions=管理分区
      800.create-an-index-on-a-partitioned-table=创建分区表索引
    300.manage-replicas=管理副本
    400.manage-locality=管理 Locality
    500.load-balancing=负载均衡
      300.manually-manage-load-balancing=手动管理负载均衡
  700.high-data-availability=数据高可用
    100.administrator-guide-flashback=闪回
    200.backup-and-recovery-management=备份恢复管理
      300.cluster-level-data-backup=备份数据（集群级别）
      400.data-recovery=恢复数据
      500.routine-maintenance=日常维护
  800.administrator-guide-monitoring-and-alerts=监控和告警
    100.use-ocp-to-monitor-databases=通过 OCP 监控数据库
      200.monitoring=监控
      300.alerts=告警
700.developer-guide=开发者指南
  100.foreword=前言
    300.about-oceanbase-database=关于 OceanBase 数据库
      400.about-how-to-access-oceanbase-database=关于 OceanBase 数据库访问方式
  200.connect-to-oceanbase-database=连接 OceanBase 数据库
    500.query-table-data=查询表数据
      500.use-operators-and-functions-in-a-query=在查询中使用操作符和函数
  300.dml-statements-and-transactions=DML 语句和事务
    100.about-dml-statements=关于 DML 语句
  400.create-and-manage-database-objects=创建和管理数据库对象
    200.create-and-manage-tables=创建和管理表
    300.create-and-manage-partitioned-tables=创建和管理分区表
    400.create-and-manage-table-groups=创建和管理表组
    500.create-and-manage-views=创建和管理视图
  500.migrate-data-to-oceanbase-database=向 OceanBase 数据库迁移数据
  600.appendix=附录
800.best-practices=最佳实践
900.supporting-tools=生态工具
  100.ob-admin=ob-admin
  200.ob-agent=OBAgent
    100.about-obagent=关于 OBAgent
    200.configuration-reference=配置引用
    300.install-and-deploy-obagent=安装部署
    400.obagent-metrics=OBAgent 指标
  400.cdc=CDC
    200.liboblog=liboblog
      100.deploy-and-use-liboblog=liboblog 部署和使用
      200.liboblog-parameters=liboblog 参数说明
    300.oblogproxy=oblogproxy
      100.install-and-deploy-oblogproxy=安装部署
    400.oblogmsg=oblogmsg
  600.tableapi=TableAPI
    100.introduction-to-tableapi=TableAPI 介绍
    200.use-of-the-tableapi-client=客户端使用
  800.hbaseapi=HBaseAPI
1000.sql-reference=SQL 参考
  100.elements=基本元素
    100.data-types=数据类型
      200.numeric-data-types=数值类型
      300.date-and-time-data-types=日期时间类型
      400.character-data-types=字符类型
      500.blob-and-text-data-types=大对象和文本类型
    200.expressions=表达式
    300.character-sets-and-collations=字符集与字符序
    400.literals=字面量
  200.operators=运算符
  300.functions=函数
    200.single-row-functions=单行函数
      100.date-and-time-functions=日期时间函数
      200.string-functions=字符串函数
      300.conversion-functions=转换函数
      400.mathematical-functions=数学函数
      500.comparison-functions=比较函数
      600.process-control-functions=流程控制函数
    300.aggregate-functions=聚合函数
    400.analytic-functions=分析函数
    500.encryption-functions=加密函数
    600.information-functions=信息函数
    700.other-functions=其他函数
  400.queries-and-subqueries=查询和子查询
  500.sql-statements=SQL语句
    600.alter-system=ALTER SYSTEM
    5600.sql-statements-select=SELECT
1100.sql-tuning-guide=SQL 调优指南
  200.sql-execution-plan=SQL 执行计划
    200.execution-plan-operators=执行计划算子
  300.distributed-execution-plan=分布式执行计划
  400.sql-tuning=SQL 优化
    300.monitor-the-sql-execution-performance=SQL 执行性能监控
      400.examples-of-sql-performance-analysis=SQL 性能分析示例
    400.query-rewrite=查询改写
    500.query-optimization=查询优化
      100.access-path=访问路径
      200.join-algorithm=联接算法
    600.manage-execution-plans=管理执行计划
1200.reference-guide=参考指南
  100.system-views=系统视图
    100.dictionary-views=字典视图
    200.performance-views=性能视图
  200.system-variables=系统变量
  300.system-configuration-items=系统配置项
  400.error-codes=错误码
1300.community-contribution=社区贡献
