100.learn-more-about-oceanbase=OceanBase 简介
  400.compatibility-with-oracle=与 Oracle 兼容性对比
200.quickstart=快速上手
  200.get-started-with-oceanbase-sql=上手 OceanBase SQL
  300.create-sample-application-of-mysql-mode=基于 MySQL 模式创建示例应用程序
  300.create-sample-application-of-oracle-mode=基于 Oracle 模式创建示例应用程序
  500.experience-advanced-features-of-oceanbase=体验 OceanBase 高级特性
    100.experience-scalable-oltp=体验 Scalable OLTP
400.deploy=部署数据库
  300.deploy-oceanbase-enterprise-edition=部署 OceanBase 企业版
    200.preparations-before-deploy=部署前准备
    300.deploy-through-a-graphical-interface=使用图形化界面部署
      100.configuring-the-deploy-environment-through-oat=通过 OAT 配置部署环境
      200.deploy-ocp-use-oat=部署 OCP
      300.deploy-oceanbase-cluster-use-ocp=使用 OCP 部署 OceanBase 集群
    400.deploy-through-the-command-line=使用命令行部署
      100.configure-a-deployment-environment-command-line=通过 oatcli 配置部署环境
      200.deploy-the-oceanbase-cluster-command-line=使用命令行部署 OceanBase 集群
  500.deploy-oceanbase-database-community-edition=部署 OceanBase 社区版
    200.local-deployment=本地部署
      200.environment-and-configuration-checks=部署前配置
      400.deploy-by-ui=通过图形化界面部署