100.learn-more-about-oceanbase=OceanBase の紹介
  400.compatibility-with-oracle=Oracle との互換性比較
200.quickstart=クイックスタート
  200.get-started-with-oceanbase-sql=OceanBase SQL を始める
  300.create-sample-application-of-mysql-mode=MySQL モードでのサンプルアプリケーション作成
  300.create-sample-application-of-oracle-mode=Oracle モードでのサンプルアプリケーション作成
  500.experience-advanced-features-of-oceanbase=OceanBase の高度な機能の体験
    100.experience-scalable-oltp=Scalable OLTP の体験
400.deploy=データベースのデプロイ
  300.deploy-oceanbase-enterprise-edition=OceanBase Enterprise Edition のデプロイ
    200.preparations-before-deploy=デプロイ前の準備
    300.deploy-through-a-graphical-interface=グラフィカルユーザーインターフェースを使用したデプロイ
      100.configuring-the-deploy-environment-through-oat=OAT でのデプロイ環境の設定
      200.deploy-ocp-use-oat=OCP のデプロイ
      300.deploy-oceanbase-cluster-use-ocp=OCP を使用した OceanBase クラスターのデプロイ
    400.deploy-through-the-command-line=コマンドラインを使用したデプロイ
      100.configure-a-deployment-environment-command-line=oatcli でのデプロイ環境の設定
      200.deploy-the-oceanbase-cluster-command-line=コマンドラインを使用した OceanBase クラスターのデプロイ
  500.deploy-oceanbase-database-community-edition=OceanBase Community Edition のデプロイ
    200.local-deployment=ローカルデプロイ
      200.environment-and-configuration-checks=デプロイ前の設定
      400.deploy-by-ui=グラフィカルユーザーインターフェースを使用したデプロイ
620.obap=OceanBase AP
  110.obap-deploy=部署简介
  200.obap-data-design=数据表设计
    100.data-design-best-practice=数据表设计最佳实践
  300.obap-import-data=导入数据
    20.bypass-import=旁路导入
  600.obap-query=查询加速
  700.performance-tuning=性能诊断和调优
640.ob-vector-search=向量检索
  100.ob-vector-search-overview=向量检索概述
  120.ob-vector-search-quick-start=向量检索快速上手
  500.ob-vector-search-practical-tutorial=向量检索实践教程
  600.ob-vector-search-integration=AI 集成
  700.ob-vector-search-reference=向量检索参考
    900.ob-vector-search-supported-clients-and-languages=支持的客户端和语言
680.ecological-integration=生态集成
  200.orms-frameworks=ORM 框架
    100.java=Java
    300.go=Go
  300.schema-evolution=数据库版本管理
  400.data-ingestion=数据集成
  500.sql-development=SQL 开发
  600.orchestration=编排调度
  700.visualization=可视化工具
  1000.management=数据库管控
  1100.AI=AI
690.practical-tutorial=实践教程